AppFlowy-IO/AppFlowy-Collab

collab-document/src/blocks/block.rs, collab-document/src/blocks/children.rs, collab-document/src/blocks/mod.rs, collab-document/src/blocks/text.rs, collab-document/src/blocks/utils.rs, collab-document/src/document.rs, collab-document/src/error.rs, collab-document/tests/delta/block_test.rs, collab-document/tests/delta/util.rs
=> feat: refactor block, remove the data enum and type enum

collab-document/src/blocks/entities.rs, collab-document/src/document.rs, collab-document/tests/delta/block_test.rs
Document Data
<pre>
Object {
"blocks": Object {
"fSCdijWuN2": Object {
"children": String("xh4B2GEAnR"),
"data": Object {
"delta": Array [],
},
"external_id": Null,
"external_type": Null,
"id": String("fSCdijWuN2"),
"parent": String(""),
"ty": String("page"),
},
"mDWV2j-7Ks": Object {
"children": String("MyER9Jeuhd"),
"data": Object {
"delta": Array [],
},
"external_id": Null,
"external_type": Null,
"id": String("mDWV2j-7Ks"),
"parent": String("fSCdijWuN2"),
"ty": String("text"),
},
},
"meta": Object {
"children_map": Object {
"MyER9Jeuhd": Array [],
"xh4B2GEAnR": Array [
String("mDWV2j-7Ks"),
],
},
},
"page_id": String("fSCdijWuN2"),
}
</pre>
Subscribe Change Data:
Insert block after other block
<pre>
[
Object {
"delta": Array [
Object {
"Map": Object {
"Inserted": Array [ …
=> fix: modify open document test

collab-document/src/blocks/entities.rs, collab-document/src/blocks/subscribe.rs, collab-document/src/blocks/utils.rs, collab-document/tests/delta/util.rs
Feature
when we insert a new block, the change data will be like this:
It will insert new data into blocks and children_map, and update the parent's children array
<pre>
Array [
Array [
Object {
"command": String("Inserted"),
"id": String("rK-SdebxyY"),
"path": Array [
String("blocks"),
],
"value": String("{id: rK-SdebxyY, data: {}, ty: text, children: YPo4OFJ-d0, parent: HmOGFUzvzR}"),
},
],
Array [
Object {
"command": String("Inserted"),
"id": String("YPo4OFJ-d0"),
"path": Array [
String("meta"),
String("children_map"),
],
"value": String("[]"),
},
],
Array [
Object {
"command": String("Updated"),
"id": String("nmBEaTgUZV"),
"path": Array [
String("meta"),
String("children_map"),
String("nmBEaTgUZV"),
],
"value": String("[rK-SdebxyY, KXsxGYoiaX]"),
},
],
]
</pre>
When we want to update …
=> fix: modify the changes struct

collab-document/src/blocks/utils.rs
From
<pre>
"[egNlDmdie7, PhpHVe_Yss]"
</pre>
To
<pre>
"[\"egNlDmdie7\",\"PhpHVe_Yss\"]"
</pre>
=> Parse BlockEventPayload value

collab-document/src/document.rs, collab-document/tests/delta/util.rs
=> Modify create and create with data

.github/workflows/code_coverage.yml, collab-folder/src/core/folder.rs, collab-folder/src/core/relation.rs, collab-folder/src/core/view.rs, collab-folder/src/core/workspace.rs, collab-folder/tests/folder_test/child_views_test.rs, collab-folder/tests/folder_test/serde_test.rs, collab-folder/tests/folder_test/view_test.rs
When clicking the + button, we want to insert the new page at the first index instead of the last position.
This PR is for supporting the insertion of the view at the given index.
=> feat: support insert view at index

collab-folder/src/core/view.rs, collab-folder/tests/folder_test/child_views_test.rs, collab-folder/tests/folder_test/favorite_test.rs, collab-folder/tests/folder_test/serde_test.rs, collab-folder/tests/folder_test/util.rs, collab-folder/tests/folder_test/view_test.rs
Add the "icon" field and enable it to be modified through the interface. When the "icon" changes, it should trigger the observation of the current "view_map".
=> fix: update view icon

collab-folder/src/entities.rs, collab-folder/src/folder.rs, collab-folder/src/folder_migration.rs, collab-folder/src/macros.rs, collab-folder/src/section.rs, collab-folder/src/view.rs, collab-folder/src/workspace.rs, collab-folder/tests/folder_test/child_views_test.rs, collab-folder/tests/folder_test/custom_section.rs, collab-folder/tests/folder_test/favorite_test.rs, collab-folder/tests/folder_test/main.rs, collab-folder/tests/folder_test/recent_views_test.rs, collab-folder/tests/folder_test/serde_test.rs, collab-folder/tests/folder_test/util.rs, collab-folder/tests/folder_test/view_test.rs
- Added last_edited_time
- Added last_edited_by
- Added created_by
- Fixed the timestamp from created_at always equal to 0
- Added recent section
=> feat: add last_edited_time, last_edited_by, created_by and recent section

collab-database/src/rows/row.rs, collab-database/src/rows/row_meta.rs, collab-database/tests/database_test/row_test.rs, collab-persistence/src/doc.rs, collab-plugins/src/local_storage/rocksdb.rs
Relates: https://github.com/AppFlowy-IO/AppFlowy/issues/3522
=> feat: add is_document_empty to RowMeta

Cargo.lock, collab-document/tests/blocks/text_test.rs, collab/Cargo.toml, collab/src/core/text_wrapper.rs
=> fix: cjk delta len error

collab-database/src/rows/row.rs, collab-database/src/rows/row_meta.rs
Note: This PR is not up to date with main INTENTIONALLY, as the private section commit on the collab main branch is not compatible with the main branch on the AppFlowy repo
=> chore: serde row detail

collab-document/src/document.rs, collab-document/src/document_awareness.rs, collab-document/src/lib.rs
expose the Awareness API to support collaboration selection and collaboration user management.
=> feat: support collab selection

collab-document/src/document.rs
use `event.awareness_state().full_update()` instead of `awareness_update` to get all the states
=> fix: use full update from awareness to get all the states

collab-document/src/document.rs, collab-document/src/document_awareness.rs, collab-document/tests/document/awareness_test.rs
This PR fixes retrieving awareness state after it has been set. It includes test to prove that the fix works.
=> fix: enable correct awareness retrieval

Cargo.lock, collab-plugins/Cargo.toml
https://github.com/rust-rocksdb/rust-rocksdb/pull/868
=> chore: update rocksdb version 0.22.0

collab-document/src/conversions/mod.rs, collab-document/src/conversions/plain_text.rs, collab-document/src/document.rs, collab-document/src/error.rs, collab-document/src/lib.rs, collab-document/tests/conversions/mod.rs, collab-document/tests/conversions/plain_text_test.rs, collab-document/tests/main.rs
Add a new API to convert document to plain text: `convert_document_to_plain_text`
=> feat: convert document to plain text

collab-database/src/blocks/block.rs, collab-database/src/database.rs, collab-database/src/error.rs, collab-database/src/views/view_observer.rs, collab-database/src/workspace_database/manager.rs, collab-database/tests/database_test/view_test.rs
separate create database row and get database row
=> fix: database load

Cargo.lock, collab-database/Cargo.toml, collab-database/src/blocks/block.rs, collab-database/src/database.rs, collab-database/src/rows/row.rs, collab-database/src/workspace_database/database_meta.rs, collab-database/src/workspace_database/manager.rs, collab-database/tests/database_test/encode_collab_test.rs, collab-database/tests/user_test/database_test.rs, collab-database/tests/user_test/helper.rs, collab-plugins/src/local_storage/kv/doc.rs, collab-plugins/src/local_storage/rocksdb/rocksdb_plugin.rs
1. write collab in rocksdb plugin
2. fix database row meta
=> fix: rocksdb plugin

collab-database/src/blocks/block.rs, collab-database/src/database.rs, collab-database/src/rows/row.rs, collab-database/tests/database_test/helper.rs, collab-document/src/document.rs, collab-folder/src/folder.rs, collab-folder/tests/folder_test/serde_test.rs, collab-folder/tests/folder_test/util.rs, collab-folder/tests/folder_test/workspace_test.rs, collab-plugins/src/local_storage/rocksdb/rocksdb_plugin.rs, collab-user/src/user_awareness.rs, collab-user/tests/util.rs
check collab is valid before open it with corresponding collab type object.
=> chore: check before open collab

collab-document/src/document.rs, collab-document/tests/blocks/block_test.rs
Support updating the existing block's external ID and external type.
=> feat: support update external id and external type

collab-database/src/workspace_database/body.rs
Move add database and batch add database method so that we can use the method when we plan to pass in a transaction.
Once we migrated the clients to use the body as opposed to the workspace database, we can stop returning transaction for workspace database methods.
=> feat: move add database methods to body

collab-folder/src/space_info.rs
- add default serde to SpacePermission (tested in AppFlowy)
~~Don't merge. It needs to be tested on AppFlowy first.~~
=> chore: add default serde to SpacePermission

collab-folder/src/hierarchy_builder.rs
Test should be within test module, otherwise tokio test will be introduced as an dependencies to callers that use them.
=> fix: tokio test should be within the test module

collab-database/tests/user_test/helper.rs, collab-entity/src/collab_object.rs, collab-plugins/src/local_storage/rocksdb/snapshot_plugin.rs, collab-plugins/tests/disk/script.rs, collab/src/core/origin.rs
- Add ability to parse `CollabOrigin` string.
- Add `Copy` trait to `CollabType`
=> Collab origin parse

collab-folder/src/folder.rs, collab-folder/src/macros.rs, collab-folder/src/section.rs
Method to move a section item to after another.
=> chore: function to move section

collab-plugins/src/local_storage/kv/doc.rs
We explicitly convert to a string slice to ensure proper handling when the passed value is a Uuid. Previously, we worked with String values, but now that we’re using Uuid, the conversion via AsRef behaves differently between Uuid and String. This explicit use of str helps avoid any unexpected behavior.
=> chore: explict use str instead of using asRef<u8>

collab-database/src/rows/row.rs
yjs currently doesn't support any type which is not supported in json format. This includes big integer. As a result, the only way for a yjs map to be converted to the equivalent row is to encoded the big integer in string format. By default, Rust is unable to deserialize string to i64, so a custom deserialization method has to be provided.
=> feat: handle conversion from string to i64

.github/workflows/build.yml
Add iOS, Android, macOS, Linux and Windows build CIs
=> chore: add build ci job

collab-database/src/fields/type_option/select_type_option.rs, collab-database/src/template/option_parse.rs
=> feat: add premium select option colors
