AppFlowy-IO/AppFlowy-Collab

collab-persistence/Cargo.toml

Fixes building rocksdb on certain machines, especially those using GCC13
ref: https://github.com/rust-rocksdb/rust-rocksdb/issues/772

chore: bump rocksdb crate version

---

Cargo.lock
collab-database/Cargo.toml
collab-database/src/database.rs
collab-database/src/views/field_settings.rs
collab-database/src/views/layout.rs
collab-database/src/views/mod.rs
collab-database/src/views/view.rs
collab-database/src/views/view_map.rs
collab-database/tests/database_test/field_setting_test.rs
collab-database/tests/database_test/field_test.rs
collab-database/tests/database_test/helper.rs
collab-database/tests/database_test/mod.rs
collab-database/tests/database_test/restore_test.rs
collab-database/tests/database_test/type_option_test.rs
collab-database/tests/database_test/view_test.rs
collab-database/tests/helper/util.rs
collab-database/tests/user_test/async_test/script.rs
collab-database/tests/user_test/helper.rs
collab-database/tests/user_test/type_option_test.rs
collab/src/core/any_map.rs

Introduces `field_settings`, a map in a database view that describes each field's settings. The goal is to separate the field settings in a view from the field's more inherent settings. In json format, this looks something like the following:
```
{
"field settings": {
"field_1_id": {
"is_visible": true,
"width": 100
},
"field_2_id": {
"is_visible": true,
"width": 150
},
"field_3_id": {
"is_visible": false,
"width": 50
}
}
}
```

feat: introduce per-view field settings

---

collab-database/src/database.rs
collab-database/src/macros.rs
collab-database/src/rows/row.rs
collab-database/src/views/view.rs
collab-database/src/views/view_map.rs
collab-database/tests/database_test/field_setting_test.rs
collab-database/tests/database_test/field_test.rs
collab-database/tests/database_test/helper.rs
collab-database/tests/database_test/row_test.rs
collab-database/tests/database_test/type_option_test.rs
collab-database/tests/database_test/view_test.rs
collab-database/tests/user_test/async_test/row_test.rs
collab-database/tests/user_test/async_test/script.rs
collab-database/tests/user_test/helper.rs
collab-database/tests/user_test/type_option_test.rs

Allows specifying whether the new object is pushed to the front/back, or before/after a specific object id.
Before:
- specify `prev_object_id` as `None` to push to the front, which isn't immediately clear.
- specify invalid `prev_object_id` will push back the object, leading to writing code in hacky ways, such as explicitly sending `""` as the `object_id`.
- specify `prev_object_id` to insert the object after that id.
After:
- specify `OrderObjectPosition::Start` or `OrderObjectPosition::End` to push front or back, respectively
- specify `OrderObjectPosition::Before(<object_id>)` or `OrderObjectPosition::After(<object_id>)` to insert the object relative to the `object_id`

feat: pinpoint new object location in order array

---

collab-plugins/src/local_storage/rocksdb/kv_impl.rs

closes https://github.com/AppFlowy-IO/AppFlowy/issues/4333

fix: log file name too long

---

collab-database/src/database.rs
collab-database/tests/database_test/filter_test.rs

The test `insert_database_view_filter_with_occupied_field_id_test` is inaccurate.
Inserting a filter with a `field_id` that is already the `field_id` of another filter doesn't ignore it, but still pushes instead. The test passes because the `get_filter_by_field_id` function returns only the first filter of the `ArrayRef`.
Also removing that function in particular, since the context should only know of an `id` field and leave the rest of the fields up to the filter implementation, whether it is a `Filter` in `flowy-database2` or a `TestFilter` in the tests.

fix: remove inaccurate filter test and remove get_filter_by_field_id

---

collab-folder/src/folder.rs

This method is used to get all views (nested) flattened.

feat: get all views for workspace recursively

---

collab-folder/src/folder.rs
collab-folder/src/macros.rs
collab-folder/src/view.rs
collab-folder/tests/folder_test/favorite_test.rs
collab-folder/tests/folder_test/recent_views_test.rs
collab-folder/tests/folder_test/trash_test.rs

- exclude invalid view IDs when retrieving public or private views.
- streamline section operations (add, delete, retrieve) using macros.

feat: optimize section operations

---

collab-database/src/fields/field.rs
collab-database/src/fields/field_map.rs
collab-database/tests/user_test/helper.rs

Title says all. These variables aren't in use

chore: remove visibility and width from field struct

---

Cargo.lock
Cargo.toml
collab/src/core/collab.rs
collab/tests/edit_test/awareness_test.rs

1. This PR upgrades yrs dependency to v0.18.8.
2. It also changes the behaviour of awareness update observer to what it was before #216 : now it will generate full awareness state update instead of just latest modifications.

chore: update to yrs v0.18.8

---

collab-document/src/blocks/block.rs
collab-document/src/blocks/text_entities.rs
collab-document/tests/blocks/text_test.rs
collab/src/core/text_wrapper.rs
collab/src/lib.rs

Changes:
1. Replace custom implementation of `Text::apply_delta` with a native one (introduced in yrs 0.19).
2. Update block only if its contents are different from current document state.

chore: use native impl of yrs apply delta

---

collab/src/core/collab.rs

As system time for rust std library is not meant to be used in browser environment, certain methods are disabled on the yrs library if the compilation target arch is wasm32. Therefore, to avoid compilation error for client-api-wasm, we will need to use web sys to obtain the system time instead.

feat: use js_sys to obtain clock time for wasm

---

collab-folder/src/section.rs

optimize the `try_from` function to reduce the time from 100-200us to 2-3us

fix: lazy load anyhow & timestamp in section_item

---

collab-plugins/Cargo.toml
collab-plugins/src/local_storage/rocksdb/rocksdb_plugin.rs

This PR add logging to updates and and snapshots persisted by RocksDB plugin. It also provides a `verbose_log` feature flag - when that flag is active we also will log contents of individual updates.
This is to better inspect what's stored onto disk in the future. I've observed that when using appflowy frontend app, sometimes a few user actions can cause 80-90 updates to be persisted.

chore: add tracing for persisted entries stored by rocks db plugin

---

collab-plugins/src/cloud_storage/postgres/plugin.rs
collab-plugins/src/local_storage/kv/doc.rs
collab-plugins/src/local_storage/rocksdb/rocksdb_plugin.rs
collab/src/core/collab.rs
collab/src/core/collab_plugin.rs

This PR removes `/meta/last_sync_at` field from collab along with its getters and setters. The reason for that is that setting these fields will trigger circular reaction of yrs doc updates that can easily become the majority of updates persisted and exchanged between client and server.
Also, this field data was never used for any practical purposes.

chore: remove last sync at field from collab

---

collab-document/src/document.rs
collab/src/core/collab.rs

This PR enables us to create `DocumentBody` straight from the `Collab` in readonly mode. The reason for that is that sometimes we want to be able to execute `Document`-specific operations without having direct access to a `Document` instance. Example: on the server side, we don't distinguish between different collab types, yet document indexer should be able to access `Document`-specific API.

chore: enable to get document data straight from collab

---

collab-database/Cargo.toml
collab-database/src/blocks/block.rs
collab-database/src/database.rs
collab-database/src/entity.rs
collab-database/src/fields/field_map.rs
collab-database/src/template/util.rs
collab-database/src/views/define.rs
collab-database/src/views/mod.rs
collab-database/src/views/view.rs
collab-database/src/views/view_map.rs
collab-database/src/workspace_database/manager.rs
collab-database/tests/database_test/cell_test.rs
collab-database/tests/database_test/field_setting_test.rs
collab-database/tests/database_test/field_test.rs
collab-database/tests/database_test/filter_test.rs
collab-database/tests/database_test/group_test.rs
collab-database/tests/database_test/helper.rs
collab-database/tests/database_test/layout_test.rs
collab-database/tests/database_test/restore_test.rs
collab-database/tests/database_test/row_test.rs
collab-database/tests/database_test/sort_test.rs
collab-database/tests/database_test/type_option_test.rs
collab-database/tests/database_test/view_observe_test.rs
collab-database/tests/database_test/view_test.rs
collab-database/tests/user_test/cell_test.rs
collab-database/tests/user_test/database_test.rs
collab-database/tests/user_test/helper.rs
collab-database/tests/user_test/type_option_test.rs

Make the inline database view private. When creating a new database, it should now include two views: one for the inline view and one for the display view

chore: refactor inline view id

---

collab-database/src/fields/type_option/media_type_option.rs

I just implement the default, I find it cleaner as opposed to this:
```rust
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MediaTypeOption {
#[serde(default = 'make_true')]
pub hide_file_names: bool,
}
fn make_true() -> bool {
true
}
```

fix: default hide file names to true

---

collab-document/tests/importer/md_importer_customer_test.rs

For list-type items, if the image is at a nested level, it will be parsed as a child of the list item.
For paragraphs, if the image is at a nested level, it will be parsed as a sibling of the paragraph.

test: add image test for md_importer

---

collab-database/src/workspace_database/body.rs

Return transaction for workspace database operation, so that the callers can get the encoded update.

feat: return transaction for workspace database operation

---

collab-document/src/document.rs
collab-document/tests/document/awareness_test.rs

One of the bugs that we received mentioned that the list of active collaborators only contains the latest updated user instead of all of them. This PR fixes it and adds the test to confirm the correct behavior.

fix: awareness state observer should emit state for all users

---

collab-database/src/fields/type_option/date_type_option.rs

Add a new constructor for `DateCellData`, `from_timestamp_include_time`, which set `include_time` to `true` during initialization.

feat: include time for from timestamp

---

collab-folder/src/hierarchy_builder.rs
collab-folder/src/lib.rs
collab-folder/src/space_info.rs
collab-folder/src/view.rs
collab-folder/tests/folder_test/main.rs
collab-folder/tests/folder_test/space_info_test.rs
collab-importer/src/notion/importer.rs
collab-importer/src/space_view.rs

- Removed the hardcoded keys.
- Added an icon and icon color to the space info.
- Added more built-in functions to enhance the view's extra data.
```rs
pub struct SpaceInfo {
/// Whether the view is a space view.
pub is_space: bool,
/// The permission of the space view.
///
/// If the space_permission is none, the space view will use the SpacePermission::PublicToAll.
pub space_permission: SpacePermission,
/// The created time of the space view.
pub space_created_at: i64,
/// The space icon.
///
/// If the space_icon is none, the space view will use the default icon.
pub space_icon: Option<String>,
/// The space icon color.
///
/// If the space_icon_color is none, the space view will use the default icon color.
/// The value should be a valid hex color code: 0xFFA34AFD
pub …
```

chore: refactor space info

---

collab-folder/src/hierarchy_builder.rs

Space create at key was not added to extra when building with space info.

fix: add space created at key when creating with space info

---

collab-folder/src/folder.rs
collab-folder/src/space_info.rs

Current view should be set and retrieved on per user id basis, instead of per workspace. Otherwise, a user will be able to view the last visited page for another user, even if the user has no permission to view it.

fix: current view should be updated on a per user basis instead of workspace

---

collab-folder/src/view.rs

When adding new child view, the creation time of the parent shouldn't be modified.

fix: parent view creation time shouldn't be updated when child is added

---

collab-folder/src/folder.rs

There are some edge cases where there is a cycle in a folder tree, which can lead to stack overflow. To break the cycle, we add an additional condition such that the traversal stops when a view id has been traversed before.

fix: avoid infinite recusion due to cyclic dependency

---

collab-user/src/reminder.rs

Fix: the key of `set_is_read` should be `REMINDER_IS_READ` instead of  `REMINDER_IS_ACK`

fix: using wrong update key for reminder

---

collab-document/src/document.rs
collab-document/src/utils.rs
collab-document/tests/conversions/plain_text_test.rs
collab-document/tests/importer/md_importer_test.rs
collab-importer/tests/notion_test/import_test.rs

This PR replaces `Document::to_plain_text` with `Document::paragraphs` returning blocks as plain text paragraph list, which is more versatile option:
1. We can group paragraphs together: for the purpose of future text chunking for the appflowy-cloud document indexer.
2. `new_line_each_paragraph` parameter is not necessary: just use `Document::paragraphs().join("\n")` if necessary.
3. `empty_space_each_delta` parameter is also not necessary: current logic trims the preceding and leading whitespaces but only adds extra spaces only if we actually trimmed the content.

chore: replace document plain text with paragraphs

---

collab-database/tests/user_test/database_test.rs

Get first database view id is not guaranteed to be the inline view id, which cause the test to fail from time to time.

fix: flaky create database test

---

Cargo.lock
Cargo.toml
collab-database/Cargo.toml
collab-document/Cargo.toml
collab-entity/Cargo.toml
collab-entity/src/proto/collab.rs
collab-folder/Cargo.toml
collab-folder/src/folder.rs
collab-folder/src/folder_observe.rs
collab-folder/src/lib.rs
collab-folder/src/relation.rs
collab-folder/src/revision.rs
collab-folder/src/section.rs
collab-folder/src/view.rs
collab-folder/tests/folder_test/main.rs
collab-folder/tests/folder_test/replace_view_test.rs
collab-importer/Cargo.toml
collab-plugins/Cargo.toml
collab-plugins/src/cloud_storage/channel.rs
collab-plugins/src/cloud_storage/remote_collab.rs
collab-plugins/src/cloud_storage/sink.rs
collab-user/Cargo.toml
collab/Cargo.toml
collab/src/core/collab.rs
collab/src/core/mod.rs
collab/src/core/revisions.rs
collab/src/lock/lock_timeout.rs
collab/tests/edit_test/mod.rs
collab/tests/edit_test/revision_test.rs

This PR adds concept of revisions: "bookmarks" used to timestamp collab state into specific point in time.
This PR heavy relies on document having its garbage collection turned off, since this is what yrs Snapshots require. However garbage is not bound to be kept forever, since removing outdated revisions can trigger garbage collection for data that is no longer used by any revision.

Document history

---

Cargo.lock
collab-folder/Cargo.toml
collab-folder/src/entities.rs
collab-folder/src/folder.rs
collab-folder/src/folder_migration.rs
collab-folder/src/folder_observe.rs
collab-folder/src/hierarchy_builder.rs
collab-folder/src/relation.rs
collab-folder/src/revision.rs
collab-folder/src/section.rs
collab-folder/src/view.rs
collab-folder/src/workspace.rs
collab-folder/tests/folder_test/child_views_test.rs
collab-folder/tests/folder_test/custom_section.rs
collab-folder/tests/folder_test/favorite_test.rs
collab-folder/tests/folder_test/replace_view_test.rs
collab-folder/tests/folder_test/serde_test.rs
collab-folder/tests/folder_test/trash_test.rs
collab-folder/tests/folder_test/util.rs
collab-folder/tests/folder_test/view_test.rs
collab-folder/tests/folder_test/workspace_test.rs
collab-importer/src/notion/importer.rs
collab-importer/src/space_view.rs
collab-importer/src/workspace/folder_collab_remapper.rs
collab-importer/src/workspace/id_mapper.rs
collab-importer/tests/workspace/folder_collab_remapper.rs
collab-importer/tests/workspace/workspace_remapper_test.rs
collab/src/any_mut.rs

This PR replaced view ID type from `String` into dedicated `ViewId` alias (which under the hood is `Arc<str>`). The reason is that in many cases we're cross referencing views by IDs all over the place (ID mappings, parent-child relations etc.), doing a lot of string copying (which in Rust means deep copy, together with contents). Using Arc is much simpler, faster and occupies less space.

chore: change view id type from String to Arc<str>
